title: Peter Dyson, Phd
logo: /assets/profile.jpg
description: Peter Dyson - Risk Modelling | Data Science | Cyber
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
# https://github.com/pages-themes/minimal/tree/master
# https://jekyllrb.com/docs/variables/
